version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './mysqlconf:/etc/mysql/conf.d/:rw'
      - './mysqldata:/var/lib/mysql:rw'
      - '/etc/localtime:/etc/localtime:ro'
      - '/etc/timezone:/etc/timezone:ro'
    network_mode: "host"
  jira:
    image: daocloud.io/marcus_li/jira:latest
    depends_on:
      - mysql
    network_mode: "host"
    volumes:
      - './jira/home:/var/atlassian/jira'
      - './jira/logs:/opt/atlassian/jira/logs'
  confluence:
    image: daocloud.io/marcus_li/confluence:latest
    depends_on:
      - mysql
    network_mode: "host"
    volumes:
      - './confluence/home:/var/atlassian/confluence'
      - './confluence/logs:/opt/atlassian/confluence/logs'

